// <auto-generated />
using MathTestSystem.Infrasturcture.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MathTestSystem.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260208231215_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("MathTestSystem.Domain.Entites.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Exam");
                });

            modelBuilder.Entity("MathTestSystem.Domain.Entites.ExamResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectTasks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncorrectTasks")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTasks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ExamResults");
                });

            modelBuilder.Entity("MathTestSystem.Domain.Entites.ExamTaskResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExamResultId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExamResultId");

                    b.ToTable("ExamTaskResults");
                });

            modelBuilder.Entity("MathTestSystem.Domain.Entites.MathTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualResult")
                        .HasColumnType("REAL");

                    b.Property<int?>("ExamId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ExpectedResult")
                        .HasColumnType("REAL");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("MathTask");
                });

            modelBuilder.Entity("MathTestSystem.Domain.Entites.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastName = "Swift",
                            Name = "Ana",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            LastName = "Jolie",
                            Name = "John",
                            TeacherId = 1
                        });
                });

            modelBuilder.Entity("MathTestSystem.Domain.Entites.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastName = "Smith",
                            Name = "William"
                        });
                });

            modelBuilder.Entity("MathTestSystem.Domain.Entites.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "123",
                            ProfileId = 1,
                            Role = 2,
                            Username = "williamTeacher"
                        },
                        new
                        {
                            Id = 2,
                            Password = "123",
                            ProfileId = 1,
                            Role = 1,
                            Username = "anaStudent"
                        },
                        new
                        {
                            Id = 3,
                            Password = "123",
                            ProfileId = 2,
                            Role = 1,
                            Username = "johnStudent"
                        });
                });

            modelBuilder.Entity("MathTestSystem.Domain.Entites.Exam", b =>
                {
                    b.HasOne("MathTestSystem.Domain.Entites.Student", null)
                        .WithOne("Exam")
                        .HasForeignKey("MathTestSystem.Domain.Entites.Exam", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MathTestSystem.Domain.Entites.ExamResult", b =>
                {
                    b.HasOne("MathTestSystem.Domain.Entites.Student", "Student")
                        .WithMany("Exams")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MathTestSystem.Domain.Entites.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MathTestSystem.Domain.Entites.ExamTaskResult", b =>
                {
                    b.HasOne("MathTestSystem.Domain.Entites.ExamResult", "ExamResult")
                        .WithMany("ExamTasks")
                        .HasForeignKey("ExamResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamResult");
                });

            modelBuilder.Entity("MathTestSystem.Domain.Entites.MathTask", b =>
                {
                    b.HasOne("MathTestSystem.Domain.Entites.Exam", null)
                        .WithMany("MathTasks")
                        .HasForeignKey("ExamId");
                });

            modelBuilder.Entity("MathTestSystem.Domain.Entites.Student", b =>
                {
                    b.HasOne("MathTestSystem.Domain.Entites.Teacher", "Teacher")
                        .WithMany("Students")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MathTestSystem.Domain.Entites.Exam", b =>
                {
                    b.Navigation("MathTasks");
                });

            modelBuilder.Entity("MathTestSystem.Domain.Entites.ExamResult", b =>
                {
                    b.Navigation("ExamTasks");
                });

            modelBuilder.Entity("MathTestSystem.Domain.Entites.Student", b =>
                {
                    b.Navigation("Exam")
                        .IsRequired();

                    b.Navigation("Exams");
                });

            modelBuilder.Entity("MathTestSystem.Domain.Entites.Teacher", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
